networks:
  bis_network:
    external: true

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - bis_network
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: "0"
    restart: unless-stopped


  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - bis_network

  nginx1:
    image: nginx
    container_name: nginx1
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    networks:
      - bis_network


  nginx2:
    image: nginx
    container_name: nginx2
    ports:
      - "8089:80"
      - "8444:443"
    networks:
      - bis_network

volumes:
  jenkins_config:
  jenkins_data:
